/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.helio.app;

public final class R {
  public static final class color {
    /**
     * Neutral colors
     */
    public static final int background=0x7f010000;
    public static final int bg_high=0x7f010001;
    public static final int bg_low=0x7f010002;
    public static final int bg_medium=0x7f010003;
    /**
     * Status & Risk Triage Colors
     */
    public static final int bg_urgent=0x7f010004;
    public static final int divider=0x7f010005;
    public static final int md_theme_onPrimary=0x7f010006;
    public static final int md_theme_onSecondary=0x7f010007;
    /**
     * Brand colors
     */
    public static final int md_theme_primary=0x7f010008;
    public static final int md_theme_secondary=0x7f010009;
    public static final int surface=0x7f01000a;
    public static final int text_high=0x7f01000b;
    public static final int text_low=0x7f01000c;
    public static final int text_medium=0x7f01000d;
    public static final int text_primary=0x7f01000e;
    public static final int text_secondary=0x7f01000f;
    public static final int text_urgent=0x7f010010;
  }
  public static final class drawable {
    public static final int card_background=0x7f020000;
  }
  public static final class id {
    public static final int btn_demo_chest_pain=0x7f030000;
    public static final int btn_demo_child_fever=0x7f030001;
    public static final int btn_demo_fever_conf=0x7f030002;
    public static final int btn_demo_hand_cut=0x7f030003;
    public static final int btn_demo_pregnancy=0x7f030004;
    public static final int btn_demo_water_burn=0x7f030005;
    public static final int btn_process_triage=0x7f030006;
    public static final int btn_save_record=0x7f030007;
    public static final int btn_share_referral=0x7f030008;
    public static final int btn_toggle_json=0x7f030009;
    public static final int et_clinical_notes=0x7f03000a;
    public static final int layout_history_list=0x7f03000b;
    public static final int layout_red_flags=0x7f03000c;
    public static final int layout_result_container=0x7f03000d;
    public static final int tv_confidence_score=0x7f03000e;
    public static final int tv_first_aid_list=0x7f03000f;
    public static final int tv_no_history=0x7f030010;
    public static final int tv_recommended_action=0x7f030011;
    public static final int tv_red_flags_list=0x7f030012;
    public static final int tv_referral_card_text=0x7f030013;
    public static final int tv_structured_json_output=0x7f030014;
    public static final int tv_triage_level_badge=0x7f030015;
  }
  public static final class layout {
    public static final int activity_main=0x7f040000;
  }
  public static final class style {
    public static final int Theme_Helio=0x7f050000;
  }
}